<?xml version="1.0" encoding="UTF-8"?>
<project default="xar" name="EditionExample" basedir=".">
    
    <!-- import version and name from expath package file -->
    <xmlproperty file="expath-pkg.xml"/>

    <!-- define more properties -->
    <property name="project.version" value="${package(version)}"/>
    <property name="project.name" value="${package(name)}"/>
    <property name="build.dir" value="dist"/>
    
    <!-- define tasks -->
    <target name="all" depends="xar"/>
    
    <!-- create build directory -->
    <target name="init">
        <mkdir dir="${build.dir}"/>
    </target>
    
    <!-- create xar file in build directory -->
    <target name="xar" depends="init">
        <zip destfile="${build.dir}/${project.name}-${project.version}.xar">
            <fileset dir=".">
                <exclude name="${build.dir}/**"/>
            </fileset>
        </zip>
    </target>
    
</project>